### ISSUE TITLE
File app/build/outputs/apk/debug/app-debug.apk does not exist: verify that file points to a binary

### ISSUE THREAD

**Issue by trancongdung12** [wzieba/Firebase-Distribution-Github-Action#92]
![image](https://user-images.githubusercontent.com/55046284/205261828-d3caef86-7531-4ae4-acba-36dcb723ae84.png)

How I can find the folder to save apk file

**Comment by trancongdung12** [comment]
This is fixed by me? to add android like that     android/app/build/outputs/apk/debug/app-debug.apk

**Comment by anup350** [comment]
I'm getting this error even if provide absolute path to apk file. @trancongdung12 Could you please share the steps that you used fix the issue?

`${GITHUB_WORKSPACE}/app/build/outputs/apk/release/app-release-unsigned.apk`

**Comment by LuizCristino** [comment]
> I'm getting this error even if provide absolute path to apk file. @trancongdung12 Could you please share the steps that you used fix the issue?
> 
> `${GITHUB_WORKSPACE}/app/build/outputs/apk/release/app-release-unsigned.apk`

@anup350 If you are building with react native your path is wrong, you forgot to add `/android/` between {GITHUB_WORKSPACE} and app.

The correct path is `${GITHUB_WORKSPACE}/android/app/build/outputs/apk/release/app-release-unsigned.apk`
